#Application Ports
server:
 port: 9050
 
#Service Registry Properties
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost
#Application Ports  
spring:
 application:
    name: ticket-management-service
 datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ticket-management
    username: postgres
    password: Otsi@1234
 jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   show-sql: true
 mvc:
   pathmatch:
    matching-strategy: ant-path-matcher
   
#File Properties   
 servlet:
    multipart:
      enabled: true
      file-size-threshold: 1KB
      max-file-size: 5MB
   
#Otsi Mail Properties   
 mail:
    host: webmail.otsi-usa.com
    password: Otsi&23456
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 20000
          starttls:
            enable: true
          timeout: 20000
          writetimeout: 20000
    username: easyretailworld@otsi.com
    
#Smtp Mail Properties    
 
# mail:
#    host: smtp.gmail.com
#    password: rfbpkkhrehvqchaq
#    port: 587
#    properties:
#       mail:
#        smtp:
#          auth: true
#          connectiontimeout: 80000
#          starttls:
#            enable: true
#          timeout: 80000
#          writetimeout: 80000
#    username: raoch174@gmail.com  

    
#Logging Properties
logging:
    file:
      name: C:/Users/ADMIN/Desktop/logs/ticket-management.log
    level:
      com.otsi.retail.ticketservice.service: DEBUG  
      
#Application Constants    
ticket-app:
  messages:
    ticketMailBodyTemplateFile: TICKET-EMAIL-BODY-TEMPLATE.txt
    ticketMailSubject: New Ticket has been created
    filesUploadDirectory: C:\\TicketImages