server:
 port: 9050
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.100.143.45:8762/eureka/
  instance:
    hostname: localhost
  
spring:
 application:
    name: ticket-management-service
 datasource:
    platform: postgres
    url: jdbc:postgresql://10.100.149.140:5432/ticket-management
    username: postgres
    password: Otsi@123
 jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   show-sql: true
   
 servlet:
    multipart:
      enabled: true
      file-size-threshold: 1KB
      max-file-size: 5MB
 mail:
    host: smtp.gmail.com
    password: raywuntvtunfcthq
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
    username: abc@gmail.com
    
logging:
    file:
      name: C:/Users/ADMIN/Desktop/logs/ticket-management.log
    level:
      com.otsi.retail.ticketservice.service: DEBUG  
      
ticket-app:
  messages:
    ticketMailBodyTemplateFile: TICKET-EMAIL-BODY-TEMPLATE.txt
    ticketMailSubject: Ticket Creation Successful
    filesUploadDirectory: D:\\UploadedFiles
          